#!/usr/bin/env python3
"""Epic #24 — generate docker-compose.nodes.yml: N resolver nodes forming a real Chord ring.

Nodes-mode counterpart to the master docker-compose.yml (which runs the Unbound baseline).
Here each container runs ``python -m node.run_ring_node`` on the socket transport, so the N
containers form a genuine Chord ring and answer real DNS queries — this is what lets
run_experiment produce a nodes-mode CSV (resolver_used=node-<id>), not an Unbound baseline.

Why generated (not a static compose with ``--scale``): the ring needs DETERMINISTIC identity
and addressing — node j has a fixed pk/ring-id and a stable hostname ``rpos-node-<j>`` — so
every node derives the full id->address roster from N alone (CLAUDE.md §2 reproducibility).
``--scale`` gives random hostnames/ids, which breaks the roster. So we emit one explicit
service per node with a static IP and NODE_INDEX. This file is regenerated per run and is
git-ignored.

The node image is the existing testbed/node/Dockerfile (unchanged) — we only override its
command. The DNS MANIFEST is bind-mounted read-only as the fallback zone; each node's
results/ dir is bind-mounted out so its per-query CSV (incl. Chord hop counts) lands on the
host for aggregation.

Usage:
    python3 gen_nodes_compose.py --nodes 8 [--out docker-compose.nodes.yml]
        [--plot-n 1024] [--drg-indegree 2] [--challenge-timeout 2.0] [--seed 20260919]
        [--ring-port 7000] [--dns-port 5300] [--mode honest]
"""
import argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
NET_NAME = "ringnet"
SUBNET = "172.30.0.0/24"
IP_BASE = 10          # node j -> 172.30.0.(IP_BASE + j); leaves .1 (gateway) and .2-.9 free


def _service(j: int, n: int, a) -> str:
    ip = f"172.30.0.{IP_BASE + j}"
    role = "seed" if j == 0 else "join"
    return f"""  rpos-node-{j}:
    build:
      context: ..
      dockerfile: testbed/node/Dockerfile
    image: rpos-node:latest
    container_name: rpos-node-{j}
    hostname: rpos-node-{j}
    command: ["python", "-m", "node.run_ring_node"]
    environment:
      NODE_INDEX: "{j}"
      NODES: "{n}"
      SEED_INDEX: "0"
      NODE_NAME_PREFIX: "rpos-node-"
      RING_PORT: "{a.ring_port}"
      DNS_PORT: "{a.dns_port}"
      ZONE_JSON: "/zones/MANIFEST.json"
      PLOT_N: "{a.plot_n}"
      DRG_INDEGREE: "{a.drg_indegree}"
      CHALLENGE_TIMEOUT: "{a.challenge_timeout}"
      SEED: "{a.seed}"
      MALICIOUS_MODE: "{a.mode}"
      MAINT_INTERVAL: "1.0"
      REPLICATION: "{a.replication}"
      SUCC_LIST_LEN: "{a.succ_list_len}"
      RING_IP_PREFIX: "172.30.0"
      RING_IP_BASE: "{IP_BASE}"
    volumes:
      - ../testbed/dns/zones/MANIFEST.json:/zones/MANIFEST.json:ro
      - ../results/ring/{j}:/app/node/results
    healthcheck:
      test: ["CMD", "python", "-c",
             "import socket; socket.create_connection(('127.0.0.1', {a.ring_port}), 2).close()"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    networks:
      {NET_NAME}:
        ipv4_address: {ip}
    # role={role}
"""


def render(n: int, a) -> str:
    services = "\n".join(_service(j, n, a) for j in range(n))
    return f"""# GENERATED by gen_nodes_compose.py (epic #24) — do not edit by hand; regenerated per run.
# {n} resolver nodes forming a real Chord ring over sockets (node/run_ring_node.py).
# Seed = rpos-node-0; the rest join via it. Bring up:
#   docker compose -f docker-compose.nodes.yml up -d --build
name: rpos-ring

services:
{services}
networks:
  {NET_NAME}:
    name: rpos-ring_{NET_NAME}
    driver: bridge
    ipam:
      config:
        - subnet: {SUBNET}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the nodes-mode ring compose (epic #24).")
    ap.add_argument("--nodes", type=int, required=True, help="ring size N")
    ap.add_argument("--out", type=Path, default=HERE / "docker-compose.nodes.yml")
    ap.add_argument("--plot-n", type=int, default=1024)
    ap.add_argument("--drg-indegree", type=int, default=2)
    ap.add_argument("--challenge-timeout", type=float, default=2.0)
    ap.add_argument("--seed", type=int, default=20260919)
    ap.add_argument("--ring-port", type=int, default=7000)
    ap.add_argument("--dns-port", type=int, default=5300)
    ap.add_argument("--mode", default="honest")
    # A4 (issue #35) sweeps the replication factor. Defaults = 3 (frozen PARAMETERS.md), so every
    # other experiment is unaffected. A replica set of s>4 also needs a longer successor list
    # (SUCC_LIST_LEN), applied as a runtime override in run_ring_node (chord.py stays byte-identical).
    ap.add_argument("--replication", type=int, default=3, help="chunk replication factor s")
    ap.add_argument("--succ-list-len", type=int, default=3, help="Chord successor-list length")
    a = ap.parse_args()
    if a.nodes < 1:
        ap.error("--nodes must be >= 1")
    if a.nodes > 240:
        ap.error("--nodes must be <= 240 (static /24 IP range)")
    a.out.write_text(render(a.nodes, a))
    print(f"wrote {a.out} ({a.nodes} nodes, seed=rpos-node-0, subnet {SUBNET})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
